<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
// グローバルスコープを使うため
use Illuminate\Database\Eloquent\Builder;

class Person extends Model
{
    // グローバルスコープ ageの値が20以上のレコードだけ表示
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope('age', function (Builder $builder){
           $builder->where('age', '>', 20);
        });
    }


    // id,name,ageを文字列にまとめて返す
    public function getData(): string
    {
        return $this->id . ':' . $this->name . '(' . $this->age . ')';
    }


    public function scopeNameEqual($query, $str)
    {
        return $query->where('name', $str);
    }


    // ageが〜以上
    public function scopeAgeGreaterThan($query, $n)
    {
        return $query->where('age', '>=', $n);
    }

    // ageが〜以下
    public function scopeAgeLessThan($query, $n)
    {
        return $query->where('age', '<=', $n);
    }






}
